### ISSUE TITLE
Søgninger med danske tegn giver ikke de forventede resultater

### ISSUE THREAD

**Issue by RuneMolin** [turnipsoft/virkr#140]
'Sjælland' giver 3 resultater, ingen af dem hvor 'Sjælland' indgår i virksomhedsnavnet. 'Sjaelland' giver til gengæld gevinst

**Comment by turnipsoft** [comment]
Umiddelbart, virker det da fint på virkr.dk

**Comment by ehartvig** [comment]
Kan ikke genskabes.
