### ISSUE TITLE
Encoding under tomcat

### ISSUE THREAD

**Issue by RuneMolin** [turnipsoft/virkr#141]
Når vi kører under tomcat (ERST branchen) er der ged i encoding.

Encoding i sourcefiler og html header er som det skal være (html lang burde måske være 'da'), men tomcat kører default med iso-8859-1 (som servlet specificationen siger).

Det kan f.eks. ses ved en curl:
<img width="485" alt="screen shot 2017-12-19 at 23 15 13" src="https://user-images.githubusercontent.com/8211969/34181488-9ee7ab24-e512-11e7-93cb-aa3adec86f9c.png">

Det resulterer i følgende forkerte tegn:
<img width="370" alt="screen shot 2017-12-19 at 23 14 16" src="https://user-images.githubusercontent.com/8211969/34181489-9f0537ca-e512-11e7-9f76-e630d1b5fb15.png">

Jeg ved ikke om ERST´s tomcat bliver omkonfigureret til at køre utf-8 (så vil det virke), eller der bruges standard.

Hvis standard skal bruges er der to løsninger:

1. I ERST branchen ændres .editorconfig til iso-8859-1, og der skal sikkert rettes i samtlige filer med danske tegn
2. Konfigurér et filter i Spring Boot. Se http://tomcat.apache.org/tomcat-8.0-doc/config/filter.html#Set_Character_Encoding_Filter

**Comment by turnipsoft** [comment]
Når den kører på springboot på serveren har jeg bare sat encoding som -D det virker fint
