### ISSUE TITLE
Docker postgres container skal køre, før at backenden kan køre

### ISSUE THREAD

**Issue by TheoAndersen** [turnipsoft/virkr#148]
Hvis man bare kører backenden ```./gradlew backend:start``` uden at have startet postgres docker containeren først, så fejler gradle med at den ikke kan fange postgres.

Burde dette være sat ind automatisk når backenden starter op?

eller burde det være en ekstra gradle task?

**Comment by turnipsoft** [comment]
Vi er i et vadested lige nu, man kan ikke køre med postgres backenden, fordi caching mekanismen ikke har fulgt med. Så lige p.t. kan man kun køre med mem caching hvis man vil have caching , så vælg mem caching i application.yml filen

**Comment by turnipsoft** [comment]
Jeg tror vi helt abandoner postgresen, lige meget hvad. Og hælder mest til at bruge en ElasticSearch i stedet.

**Comment by turnipsoft** [comment]
Det er følgende settings
caching: true
    cachefactory: memorymap

**Comment by turnipsoft** [comment]
helt banalt 1000 regnskaber, memorymap .-) der er implementeret der.

Men der tænker jeg bare man implementerer end rediscache eller en elasticsearchcache.. osv.

**Comment by shartvig** [comment]
Lukker, vi har forladt postgres og kommer ikke tilbage
