### ISSUE TITLE
Mem Cache skal være lidt mere intelligent

### ISSUE THREAD

**Issue by turnipsoft** [turnipsoft/virkr#154]
Der er behov for memcachen overskriver, fra tid til anden, ellers kan regnskaber potentielt ligge alt for længe

**Comment by RuneMolin** [comment]
Guava LoadingCache med en passende Eviction policy

**Comment by turnipsoft** [comment]
Et godt bud

**Comment by RuneMolin** [comment]
Ah, det er ikke helt så ligetil med det nuværende design, men jeg tror stadig guava kan anvendes

**Comment by turnipsoft** [comment]
Guava implementeret simpelt og samtidig med read ahead på grafer
