### ISSUE TITLE
Stiftelse med kapital indskud

### ISSUE THREAD

**Issue by turnipsoft** [turnipsoft/virkr#174]
Oplysning om stiftelse med indskud af kapital i andre værdier end kontanter 

Det vil være super, hvis der var oplysning om, at der er sket indskud i andre værdier end kontanter ifbm. start af virksomheden.

Det kan måske tilføjes til stamdata delen under kapital? Evt. et udråbstegn, hvis der er sket indskud, og så en foldudboks eller lignende, hvor man kan få flere oplysninger. 

Oplysning om at der er sket indskud kan findes på cvr.dk under registreringshistorik ved nederste punkt Nye selskaber.
a.       Hvis det endvidere er muligt at identificere, om indskuddet er foretaget med en vurderingsberetning fra en revisor (selskabslovens § 36) eller med en ledelseserklæring (selskabslovens § 38)
--

**Comment by turnipsoft** [comment]
selve det at det er betalt kontakt, står ikke umiddelbart i indeks.

**Comment by ehartvig** [comment]
VIR-45 er oprettet
