### ISSUE TITLE
Ny søgning laves ikke efter rettet CVR i URL

### ISSUE THREAD

**Issue by ehartvig** [turnipsoft/virkr#199]
Hvis man retter CVR i URL'en så opdateres siden ikke.

For at genskabe: 
1) gå til http://virkr.dk/#/
2) indtast CVR i søgefelt; enter 
3) ret CVR i URL til et der er forskelligt fra step 1; klik 'enter' eller reload
4) samme URL som ved step 2 vises og resultat fra step 2

**Comment by ehartvig** [comment]
Er også oprettet som VIR-30

**Comment by shartvig** [comment]
won't do
