### ISSUE TITLE
Ophørte virksomheder (som har regnskaber) vises ikke 

### ISSUE THREAD

**Issue by ehartvig** [turnipsoft/virkr#200]
Når man slår et CVR op til en ophørt virksomhed som har regnskaber på cvr.dk (se screenshot) 
så vises 'Der blev ikke fundet noget resultat på søgningen : 38231219'

Her ved eksempel til CVR: 38231219

http://virkr.dk/#/soegeresultat/38231219

Se at der ligger regnskaber 
https://datacvr.virk.dk/data/visenhed?enhedstype=virksomhed&id=38231219&soeg=&openFilter&virksomhedsform=60&virksomhedsstatus=ophoerte_virksomhedsstatus&antal_ansatte=Alle&reklamebeskyttelse=Alle&type=Alle&sortering=default&virksomhedsmarkering=Alle&kommune=Alle&region=Alle&personrolle=Alle&branche=undefined
<img width="964" alt="screen shot 2018-01-25 at 15 09 27" src="https://user-images.githubusercontent.com/29685618/35392426-1e926684-01e2-11e8-87c4-c87048f24f17.png">
<img width="950" alt="screen shot 2018-01-25 at 15 09 32" src="https://user-images.githubusercontent.com/29685618/35392427-1eace360-01e2-11e8-8b5c-e0062ab7cef6.png">

**Comment by turnipsoft** [comment]
Man kan udelukkende søge på aktuelle virksomheder p.t. på virkr og vist virksomheder som er under konkurs og under likvidation og således ikke ophørte virksomheder

**Comment by turnipsoft** [comment]
Har i stedet oprettet #201
