### ISSUE TITLE
Hvorfor vises de nyeste regnskaber ikke?

### ISSUE THREAD

**Issue by ehartvig** [turnipsoft/virkr#214]
På http://virkr.dk/#/virksomhed/24246221 kan man se regnskaber fra 2012 og 2013 men på https://datacvr.virk.dk/data/visenhed?enhedstype=virksomhed&id=24246221&soeg=24246221 kan man se regnskaber til og med 2016. 

Er det en fejl? 

<img width="1178" alt="screen shot 2018-05-09 at 14 45 37" src="https://user-images.githubusercontent.com/29685618/39815367-071ae0d2-5398-11e8-845a-36c908218d88.png">
<img width="1257" alt="screen shot 2018-05-09 at 14 45 47" src="https://user-images.githubusercontent.com/29685618/39815368-0738d330-5398-11e8-8816-a44725d9a37d.png">

**Comment by turnipsoft** [comment]
Når man kigger på indekset kan jeg ikke finde hverken XBRL eller iXBRL så det er noget uklart hvor det kommer fra.

Laver man søgning i offentliggørelsesindeks er de eneste 2 regnskaber som har XBRL dokumenter på sig, dem som også vises i virkr. 

Virkr kan jo kun vise det der ligger i offentliggørelses indeks. Det bør måske undersøges nærmere hvor virk.dk får sine links fra.
