### ISSUE TITLE
Error view efter Klik på xbrl 

### ISSUE THREAD

**Issue by ehartvig** [turnipsoft/virkr#215]
Når man på http://virkr.dk/#/virksomhed/24246221 klikker på xbrl ikonet ved 2013 og også 2012 regnskab (se screenshot), åbnes et nyt tab http://regnskaber.virk.dk/12264242/Y3ZyLmRrOi8veGJybHMvWC1BMUIxRUQzNS0yMDEzMDUwN18xMTA2MDhfOTY0.xml
med følgende fejl. 

> This page contains the following errors:
> error on line 3 at column 65: xmlns:basis: 'http://xbrl.dcca.dk/Regnskab 2.0 Basis' is not a valid URI
> Below is a rendering of the page up to the first error.

<img width="1406" alt="screen shot 2018-05-09 at 14 51 13" src="https://user-images.githubusercontent.com/29685618/39815526-83b60ac2-5398-11e8-8126-f1a1667ef290.png">
<img width="1178" alt="screen shot 2018-05-09 at 14 45 37" src="https://user-images.githubusercontent.com/29685618/39815533-8720285a-5398-11e8-853f-ea8fec4fc4b0.png">

**Comment by ehartvig** [comment]
Når man klikker på samme xbrl link på https://datacvr.virk.dk/data/visenhed?enhedstype=virksomhed&id=24246221&soeg=24246221 så downloades filen og hvis man klikker på 'åbn i nyt vindue' så vises en blank side.

**Comment by turnipsoft** [comment]
Man kan godt lave det så det virker ligesom på virk.dk den gør nemlig det at den henter regnskabet fra virk som så henter det fra ERST og sætter nogle header op til browseren om hvad det er og derfor tvinger browseren til at downloade det.

Det går virkr.dk ikke den linker bare direkte og derfor er det browseren der har ansvaret hvad den vil gøre med den.

Spørgsmålet er hvad man vil.. Jeg syntes jo selv det er irriterende den downloader som default, jeg vil hellere have XBRL vist i browseren og så evt. downloade det hvis jeg har behovet. Men det gør så at nogle browsere åbenbart ikke kan parse XML'en , men det kan virkr.dk bare ikke gøre så meget ved.

Jeg tænker vi kan rette hvis det er et ønske.
