### ISSUE TITLE
http://xbrl.dcca.dk/ifrs-dk-cor_2014-12-20 dns error

### ISSUE THREAD

**Issue by nymann** [turnipsoft/virkr#232]
I https://github.com/turnipsoft/virkr/blob/master/backend/src/main/groovy/dk/ts/virkr/aarsrapporter/parser/RegnskabNodes.groovy henviser i til dcca.dk for ifrs-dk XBRL speccet, men siden er ikke oppe længere.

Ved i tilfældigvis om den er flyttet? Eller hvor man kan få fat i ifrsdk xsd specs?

**Comment by turnipsoft** [comment]
Vi anvender altid specs direkte fra erhvervstryelsen, i filen der nævnes er der bare benævnt et XML namespace, som så også er er en URL, men som i praksis anvendes til at hente nogle specs fra.

Selve taksonomierne og dermed også XML schema hentes her :  
https://erhvervsstyrelsen.dk/vejledning-teknisk-vejledning-og-dokumentation-regnskab-20-taksonomier-aktuelle

**Comment by nymann** [comment]
Tak for det hurtige svar!
Jeg havde endda været inde på den side, jeg havde bare ikke scrollet ned. *suk*
