### ISSUE TITLE
Der mangler sourcemaps

### ISSUE THREAD

**Issue by turnipsoft** [turnipsoft/virkr#26]
Der er ikke sourcemaps med længere det er skidt

**Comment by RuneMolin** [comment]
Jeg har sourcemaps. I webpack.config.js:

    var debug = process.env.NODE_ENV !== "production";

    ...
    module.exports = {
      context: __dirname,

      devtool: debug ? "inline-sourcemap" : null,

Så med mindre du tilfældigvis har NODE_ENV sat til production skulle det virke. En clean måske ?
