### ISSUE TITLE
CORS virker local men ikke på server

### ISSUE THREAD

**Issue by turnipsoft** [turnipsoft/virkr#29]
super sært.. cors virker fint lokalt, men ikke oppe på serveren, på trods af spring boot config CrossDomain allow all.

kan testest ved at pege på virkr.dk:9092 fra react. det spiller ikke, men spiller jo fint når man kører localhost.

lige nu har virkr.dk en proxy pass så man kan komme ind til apiet, men skal have cross domain problematikken, fordi en app skal også kunne bruge apiet

**Comment by RuneMolin** [comment]
Kunne også overveje skift til jsonp: https://www.npmjs.com/package/fetch-jsonp

**Comment by turnipsoft** [comment]
Ja det kunne sagtens være det der bliver en løsning
