### ISSUE TITLE
Kald til backend

### ISSUE THREAD

**Issue by RuneMolin** [turnipsoft/virkr#41]
Som det er lavet nu er der to REST kald mod backend. De er ikke garanteret at afslutte i en bestemt rækkefølge, hvilket muligvis kan give problemer på sigt. setState bliver også kaldt to gange, hvilket er unødvendigt.

Udnyt at det er et promise, og chain dem sammen:  hentRegnskabsData.then(hentVirksomhedsData).then(setState)

Alternativt lav et composite endpoint i backend som returnerer det samlede resultat

**Comment by turnipsoft** [comment]
Giver god mening at chaine dem
