### ISSUE TITLE
Title skal ikke være tom 

### ISSUE THREAD

**Issue by ehartvig** [turnipsoft/virkr#67]
på http://virkr.dk/
er title == ""

![screen shot 2017-07-01 at 15 42 44](https://user-images.githubusercontent.com/29685618/27762548-597085f4-5e74-11e7-8e30-682b1bc460d1.png)
![screen shot 2017-07-01 at 15 43 00](https://user-images.githubusercontent.com/29685618/27762549-597132d8-5e74-11e7-8feb-343fc6c1fd67.png)

**Comment by turnipsoft** [comment]
fixed
